server:
  port: 8081
spring:
  application:
    name: oki-backup
  boot:
    admin:
      client:
        url: "http://localhost:8082"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
oki:
  backup:
    host: localhost
    userName: root
    password: kl002860
    database: springbootdemo

management:
  endpoints:
    web:
      exposure:
        include: "*"