server:
  port: 8082
spring:
  application:
    name: oki-monitor
    cloud:
      consul: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  boot:
    admin:
      discovery:
        ignored-services: consul
