spring:
  application:
    name: oki-producer
  boot:
    admin:
      client:
        url: "http://localhost:8082"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: "*"
